#

In [1]:
# Title

In [2]:
# Imports
import pandas as pd
import numpy as np

In [3]:
# Viewing Data

# Define column names
column_names = ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration','num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
               'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system',
               'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

# Read data, add column names
data = pd.read_csv('datasets/automobile/automobile/imports-85.data', header=None, names=column_names, sep=',', na_values='?')
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [4]:
# Data Preprocessing

In [14]:
# Viewing all features
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    float64
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         201 non-null    float64
 22  peak-rpm           201 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 42.4+ KB

In [13]:
data.describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,122.00000,98.797015,174.200995,65.889055,53.766667,2555.666667,126.875622,3.330711,3.256904,10.164279,103.396985,5117.587940,25.179104,30.686567,13207.129353
std,1.254802,31.99625,6.066366,12.322175,2.101471,2.447822,517.296727,41.546834,0.268072,0.316048,4.004965,37.365602,478.113178,6.423220,6.815150,7947.066342
min,-2.000000,65.00000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,101.00000,94.500000,166.800000,64.100000,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,122.00000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5117.587940,24.000000,30.000000,10295.000000
75%,2.000000,137.00000,102.400000,183.500000,66.600000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.00000,120.900000,208.100000,72.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [8]:
# Missing Values per Column
print(data.isnull().sum())

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
# Check distribution based on target variable?
target_variable = 'price'
print(f"\nTarget Variable: {target_variable}")

In [9]:
# Data Visualisation

In [10]:
data.dropna(subset=[target_variable], axis=0, inplace=True)
print(f"\nDropped rows where target '{target_variable}' was missing. New shape: {data.shape}")

# 2. Impute numerical features with the mean
numerical_cols_to_impute = ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm']
for col in numerical_cols_to_impute:
    # Ensure column is numeric before imputing
    data[col] = pd.to_numeric(data[col], errors='coerce') # Should already be numeric if loaded correctly, but safe check
    mean_val = data[col].mean()
    data[col].fillna(mean_val, inplace=True)
    print(f"Filled NaNs in numerical '{col}' with mean: {mean_val:.2f}")

# 3. Impute categorical features with the mode
categorical_cols_to_impute = ['num-of-doors']
for col in categorical_cols_to_impute:
    mode_val = data[col].mode()[0]
    data[col].fillna(mode_val, inplace=True)
    print(f"Filled NaNs in categorical '{col}' with mode: {mode_val}")

# Verify no more missing values (except maybe ones you decided not to handle)
print("\nMissing Values after Imputation:")
print(data.isnull().sum()) # Should show 0 for imputed columns


# B) Convert Categorical Features to Numerical (One-Hot Encoding)
# Identify remaining categorical columns (object type)
categorical_cols = data.select_dtypes(include='object').columns
print(f"\nCategorical columns to encode: {list(categorical_cols)}")

# Apply one-hot encoding
data_encoded = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

print("\nData after one-hot encoding (first 5 rows):")
print(data_encoded.head())
print("\nNew shape after encoding:", data_encoded.shape)


# C) Ensure Target is Numeric and Separate Features/Target
# Convert target 'price' to numeric (it might still be object if loaded with '?')
data_encoded[target_variable] = pd.to_numeric(data_encoded[target_variable], errors='coerce')

# Separate Features (X) and Target (y)
X = data_encoded.drop(target_variable, axis=1)
y = data_encoded[target_variable]

# Verify separation
print(f"\nFeatures (X) and Target (y) separated.")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)
print("Data type of y:", y.dtype) # Should be numeric now


# D) Feature Scaling (To be done within Pipeline)
# Identify numerical feature columns in the final feature set X for the scaler
numerical_features = X.select_dtypes(include=np.number).columns.tolist()
print(f"\nNumerical features identified for scaling: {len(numerical_features)}")

Dropped rows where target 'price' was missing. New shape: (201, 26)
Filled NaNs in numerical 'normalized-losses' with mean: 122.00
Filled NaNs in numerical 'bore' with mean: 3.33
Filled NaNs in numerical 'stroke' with mean: 3.26
Filled NaNs in numerical 'horsepower' with mean: 103.40
Filled NaNs in numerical 'peak-rpm' with mean: 5117.59
Filled NaNs in categorical 'num-of-doors' with mode: four

Missing Values after Imputation:
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

Categorical columns to encode: ['make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system']

Data after one-hot encoding (first 5 rows):
   symboling  normalized-losses  wheel-base  length  width  height  \
0          3              122.0        88.6   168.8   64.1    48.8
1          3              122.0        88.6   168.8   64.1    48.8
2          1              122.0        94.5   171.2   65.5    52.4
3          2              164.0        99.8   176.6   66.2    54.3
4          2              164.0        99.4   176.6   66.4    54.3

   curb-weight  engine-size  bore  stroke  ...  num-of-cylinders_three  \
0         2548          130  3.47    2.68  ...                   False
1         2548          130  3.47    2.68  ...                   False
2         2823          152  2.68    3.47  ...                   False
3         2337          109  3.19    3.40  ...                   False
4         2824          136  3.19    3.40  ...                   False

   num-of-cylinders_twelve  num-of-cylinders_two  fuel-system_2bbl  \
0                    False                 False             False
1                    False                 False             False
2                    False                 False             False
3                    False                 False             False
4                    False                 False             False

   fuel-system_4bbl  fuel-system_idi  fuel-system_mfi  fuel-system_mpfi  \
0             False            False            False              True
1             False            False            False              True
2             False            False            False              True
3             False            False            False              True
4             False            False            False              True

   fuel-system_spdi  fuel-system_spfi
0             False             False
1             False             False
2             False             False
3             False             False
4             False             False

[5 rows x 65 columns]

New shape after encoding: (201, 65)

Features (X) and Target (y) separated.
Shape of X: (201, 64)
Shape of y: (201,)
Data type of y: float64

Numerical features identified for scaling: 15

C:\Users\danie\AppData\Local\Temp\ipykernel_23060\2121118116.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(mean_val, inplace=True)
C:\Users\danie\AppData\Local\Temp\ipykernel_23060\2121118116.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(mode_val, inplace=True)

In [ ]:
# Viewing distribution of data (add) charts
print("\nValue Counts for 'body-style':")
print(data['body-style'].value_counts())

In [11]:
# --- Imports for Models and Evaluation ---
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression # For regression
from sklearn.svm import SVR # For regression
from sklearn.tree import DecisionTreeRegressor # For regression
from sklearn.neural_network import MLPRegressor # For regression

import numpy as np
import pandas as pd # Re-import if in a new script/session


print("\n--- Checking Data Types in X before Pipeline ---")
print(X.info())

K = 5 # Or K=10, your group decides
kf = KFold(n_splits=K, shuffle=True, random_state=42) # random_state for reproducibility
print(f"\nUsing K={K} for Cross-Validation.")

models_reg = {
    'Linear Regression': LinearRegression(),
    'SVR': SVR(), # Default kernel='rbf', C=1.0
    'Decision Tree Regressor': DecisionTreeRegressor(random_state=42), # No depth limit by default
    'MLP Regressor': MLPRegressor(random_state=42,
                                  max_iter=1000, # Increased iterations for convergence
                                  hidden_layer_sizes=(100,), # Default: one hidden layer with 100 neurons
                                  activation='relu', # Default activation
                                  solver='adam', # Default solver
                                  early_stopping=True, # Good practice to prevent overfitting
                                  n_iter_no_change=10) # Stops if validation score doesn't improve
}

# For the automobile 'price' prediction, it's regression
current_task = 'regression'
scoring_metric = 'neg_mean_squared_error' # Scikit-learn convention for MSE in CV
metric_name = 'Mean Squared Error (MSE)'
print(f"Task: {current_task}, Evaluation Metric: {metric_name}")


# --- Evaluation Loop using K-Fold CV ---
results = {} # Dictionary to store results

print(f"\n--- Running {K}-Fold Cross-Validation ---")

for model_name, model in models_reg.items():
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('model', model)
    ])

    scores = cross_val_score(pipeline, X, y, cv=kf, scoring=scoring_metric, n_jobs=-1) # n_jobs=-1 uses all CPU cores
    mean_score = -np.mean(scores)
    std_dev_score = np.std(scores) # Standard deviation of the scores across folds

    results[model_name] = {'Mean MSE': mean_score, 'Std Dev MSE': std_dev_score}

    print(f"{model_name}: Mean MSE = {mean_score:,.2f} (+/- {std_dev_score:,.2f})")

# --- Record Parameters (Example Notes for Report) ---

print("\n--- Parameter Notes (Example for Report) ---")
print(f"K-Fold: K={K}, shuffle=True, random_state=42")
print("Scaling: StandardScaler used within pipeline.")
print("Linear Regression: Default parameters.")
print(f"SVR: Default parameters (e.g., kernel='{SVR().kernel}', C={SVR().C}).")
print(f"Decision Tree Regressor: random_state=42, default parameters (e.g., criterion='{DecisionTreeRegressor().criterion}', max_depth=None).")
print(f"MLP Regressor: random_state=42, max_iter=1000, hidden_layer_sizes=(100,), activation='relu', solver='adam', early_stopping=True.")

# --- Convert results to DataFrame for easy reporting ---
results_df = pd.DataFrame(results).T # Transpose rows/columns
print("\n--- Summary Table for Report ---")
print(results_df.to_markdown()) # Print in Markdown format suitable for report

--- Checking Data Types in X before Pipeline ---
<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 64 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   symboling                201 non-null    int64
 1   normalized-losses        201 non-null    float64
 2   wheel-base               201 non-null    float64
 3   length                   201 non-null    float64
 4   width                    201 non-null    float64
 5   height                   201 non-null    float64
 6   curb-weight              201 non-null    int64
 7   engine-size              201 non-null    int64
 8   bore                     201 non-null    float64
 9   stroke                   201 non-null    float64
 10  compression-ratio        201 non-null    float64
 11  horsepower               201 non-null    float64
 12  peak-rpm                 201 non-null    float64
 13  city-mpg                 201 non-null    int64
 14  highway-mpg              201 non-null    int64
 15  make_audi                201 non-null    bool
 16  make_bmw                 201 non-null    bool
 17  make_chevrolet           201 non-null    bool
 18  make_dodge               201 non-null    bool
 19  make_honda               201 non-null    bool
 20  make_isuzu               201 non-null    bool
 21  make_jaguar              201 non-null    bool
 22  make_mazda               201 non-null    bool
 23  make_mercedes-benz       201 non-null    bool
 24  make_mercury             201 non-null    bool
 25  make_mitsubishi          201 non-null    bool
 26  make_nissan              201 non-null    bool
 27  make_peugot              201 non-null    bool
 28  make_plymouth            201 non-null    bool
 29  make_porsche             201 non-null    bool
 30  make_renault             201 non-null    bool
 31  make_saab                201 non-null    bool
 32  make_subaru              201 non-null    bool
 33  make_toyota              201 non-null    bool
 34  make_volkswagen          201 non-null    bool
 35  make_volvo               201 non-null    bool
 36  fuel-type_gas            201 non-null    bool
 37  aspiration_turbo         201 non-null    bool
 38  num-of-doors_two         201 non-null    bool
 39  body-style_hardtop       201 non-null    bool
 40  body-style_hatchback     201 non-null    bool
 41  body-style_sedan         201 non-null    bool
 42  body-style_wagon         201 non-null    bool
 43  drive-wheels_fwd         201 non-null    bool
 44  drive-wheels_rwd         201 non-null    bool
 45  engine-location_rear     201 non-null    bool
 46  engine-type_l            201 non-null    bool
 47  engine-type_ohc          201 non-null    bool
 48  engine-type_ohcf         201 non-null    bool
 49  engine-type_ohcv         201 non-null    bool
 50  engine-type_rotor        201 non-null    bool
 51  num-of-cylinders_five    201 non-null    bool
 52  num-of-cylinders_four    201 non-null    bool
 53  num-of-cylinders_six     201 non-null    bool
 54  num-of-cylinders_three   201 non-null    bool
 55  num-of-cylinders_twelve  201 non-null    bool
 56  num-of-cylinders_two     201 non-null    bool
 57  fuel-system_2bbl         201 non-null    bool
 58  fuel-system_4bbl         201 non-null    bool
 59  fuel-system_idi          201 non-null    bool
 60  fuel-system_mfi          201 non-null    bool
 61  fuel-system_mpfi         201 non-null    bool
 62  fuel-system_spdi         201 non-null    bool
 63  fuel-system_spfi         201 non-null    bool
dtypes: bool(49), float64(10), int64(5)
memory usage: 34.7 KB
None

Using K=5 for Cross-Validation.
Task: regression, Evaluation Metric: Mean Squared Error (MSE)

--- Running 5-Fold Cross-Validation ---
Linear Regression: Mean MSE = 7,576,543.49 (+/- 2,080,645.04)
SVR: Mean MSE = 70,982,185.66 (+/- 46,347,253.67)
Decision Tree Regressor: Mean MSE = 7,179,196.21 (+/- 2,048,227.86)
MLP Regressor: Mean MSE = 229,786,285.01 (+/- 90,037,517.48)

--- Parameter Notes (Example for Report) ---
K-Fold: K=5, shuffle=True, random_state=42
Scaling: StandardScaler used within pipeline.
Linear Regression: Default parameters.
SVR: Default parameters (e.g., kernel='rbf', C=1.0).
Decision Tree Regressor: random_state=42, default parameters (e.g., criterion='squared_error', max_depth=None).
MLP Regressor: random_state=42, max_iter=1000, hidden_layer_sizes=(100,), activation='relu', solver='adam', early_stopping=True.

--- Summary Table for Report ---
|                         |    Mean MSE |   Std Dev MSE |
|:------------------------|------------:|--------------:|
| Linear Regression       | 7.57654e+06 |   2.08065e+06 |
| SVR                     | 7.09822e+07 |   4.63473e+07 |
| Decision Tree Regressor | 7.1792e+06  |   2.04823e+06 |
| MLP Regressor           | 2.29786e+08 |   9.00375e+07 |